name: main

on:
  pull_request:
    types: [opened, reopened]

env:
  python_version: "3.9"
  poetry_version: "1.8.3"

jobs:
    static_analysis:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: ${{ env.python_version }}

          - name: Install Poetry
            uses: snok/install-poetry@v1
            with:
              version: ${{ env.poetry_version }}
              virtualenvs-create: true
              virtualenvs-in-project: true
          
          - name: Install dependencies
            run: poetry install --no-interaction --no-root
          
          - name: Linting check with Black
            run: poetry run black . --line-length 120 --check --verbose
          
          - name: Linting check with isort
            run: poetry run isort . --profile black --line-length 120 --check-only
          
          - name: Linting check with flake8
            run: poetry run flake8 src tests --max-line-length=120 --extend-ignore=E203,E266,E501,W503,F403 --statistics

    unit_testing:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.python_version }}       
    
        - name: Test with pytest
          run: poetry run pytest tests